config/routes.rb
SampleApp2::Application.routes.draw do
  root 'static_pages#home'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  class << self
    def from_users_followed_by(user)
      # 以下のやり方では、 followed_user が 5000 を越える規模になると,
      # パフォーマンスに問題がでてくる
      # where(
        # 'user_id in (:followed_user_ids) OR user_id = :user_id',
        # followed_user_ids: user.followed_user_ids,
        # user_id: user
      # )

      where <<-EOF, id: user.id
        user_id IN (
          SELECT followed_id FROM relationships WHERE follower_id = :id
        ) OR
        user_id = :id
      EOF
    end
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  before_create :create_remember_token

  has_many :microposts, dependent: :destroy

  # pepole the user follows
  has_many :relationships, foreign_key: 'follower_id',
                           dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  # user's followers
  has_many :reverse_relationships, foreign_key: 'followed_id',
                                   class_name: 'Relationship',
                                   dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  has_secure_password

  validates :name,  presence: true, length: { maximum: 50 }

  validates :email,
    presence: true,
    format: { with: /\A[\w+\-.]+@(?:[a-z\d\-]+\.)+[a-z]+\z/i },
    uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 6 }


  class << self
    def new_remember_token
      SecureRandom.urlsafe_base64
    end

    def encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
    end
  end


  def feed
    Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end


  private
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_signin_user,  only: [:create, :destroy]
  before_action :require_correct_user, only: [:destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = 'Micropost created!'
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content)
  end

  def require_correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_signin_user

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)

    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)

    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signin?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin_user,      only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :require_correct_user,     only: [:edit, :update]
  before_action :require_admin_user,       only: [:destroy]
  before_action :require_non_current_user, only: [:destroy]
  before_action :require_non_signin_user,  only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      signin @user
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 30)
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted.'
    redirect_to users_url
  end


  def following
    @title = 'Following'
    @user  = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end


  private
  def user_params
    params.require(:user).permit(
      :name, :email, :password, :password_confirmation
    )
  end

  # Before actions

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def require_non_current_user
    @user = User.find(params[:id])
    redirect_to(root_path) if current_user?(@user)
  end

  def require_admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def require_non_signin_user
    redirect_to(root_path) if signin?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def wrap(content)
    sanitize(raw(content.split.map { |s| wrap_long_string(s) }.join(' ')))
  end

  private

  def wrap_long_string(text, max_width = 30)
    zero_width_space = "&#8203;"
    regex = /.{1,#{max_width}}/
    (text.length < max_width) ? text : text.scan(regex).join(zero_width_space)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signin(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signin?
    !current_user.nil?
  end

  def signout
    self.current_user = nil
    cookies.delete(:remember_token)
  end


  def current_user=(user)
    @current_user = user
  end

  def current_user
    unless @current_user
      remember_token = User.encrypt(cookies[:remember_token])
      @current_user  = User.find_by(remember_token: remember_token)
    end
    @current_user
  end

  def current_user?(user)
    user == current_user
  end


  def redirect_back_or(default)
    logger.info default
    logger.info "redirect: #{session[:return_to]}"
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
    logger.info "SESSION DELETED"
    logger.info "redirect: #{session[:return_to]}"
  end

  def set_redirect_location
    session[:return_to] = request.url
  end


  # authorization

  def require_signin_user
    unless signin?
      set_redirect_location
      redirect_to signin_url, notice: 'Please sign in.'
    end
  end
end

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= wrap(micropost.content) %></span>
  <span class="timestamp">Posted <%= time_ago_in_words(micropost.created_at) %> ago.</span>
  <% if current_user?(micropost.user) %>
    <%= render 'shared/micropost_delete_link', micropost: micropost %>
  <% end %>
</li>

app/views/relationships/create.js.erb
$('#follow_form').html("<%= escape_javascript(render('users/unfollow')) %>")
$('#followers').html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$('#follow_form').html("<%= escape_javascript(render('users/follow')) %>")
$('#followers').html('<%= @user.followers.count %>')

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-error'>
      The form contains <%= pluralize(object.errors.count, 'error') %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li>* <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= wrap(feed_item.content) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %>
  </span>
  <% if current_user?(feed_item.user) %>
    <%= render 'shared/micropost_delete_link', micropost: feed_item %>
  <% end %>
</li>

app/views/shared/_follow_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_micropost_delete_link.html.erb
<%= link_to 'delete', micropost, method: :delete,
                                 data: { confirm: 'You sure?' },
                                 title: micropost.content %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.text_area :content, placeholder: 'Compose new micropost...' %>
  </div>

  <div id="micropost_form_footer" class="form-group">
    <span id="micropost_content_count">0</span>
    <%= f.submit 'Post', id: 'micropost_submit', class: 'btn btn-large btn-primary' %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1><%= current_user.name %></h1>
<span><%= link_to 'view my profile', current_user %></span>
<span><%= pluralize(current_user.microposts.count, 'micropost') %></span>

app/views/static_pages/_non_signin_home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: 'btn btn-large btn-primary' %>
</div>

<%= link_to image_tag('rails.png', alt: 'Rails'), 'http://rubyonrails.org/' %>

app/views/static_pages/_signin_home.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/follow_stats' %>
    </section>
    <section>
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>

  <div class="span8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if signin? %>
  <%= render 'static_pages/signin_home' %>
<% else %>
  <%= render 'static_pages/non_signin_home' %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: 'btn btn-large btn-primary' %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<% submit_button ||= @submit_button %>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, 'Confirmation' %>
  <%= f.password_field :password_confirmation %>

  <%= yield(f) if block_given? %>

  <%= f.submit submit_button, class: 'btn btn-large btn-primary' %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user),
               html: { method: :delete },
               remote: true) do |f| %>
  <%= f.submit "Unfollow", class: 'btn btn-large' %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user, size: 50 %>
        <%= @user.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/follow_stats' %>
    </section>
  </aside>

  <div class="span8">
    <% if signin? %>
      <%= render 'follow_form' %>
    <% end %>

    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to 'view my profile', @user %></span>
      <span><b>Microposts:</b><%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/follow_stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>

  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>